#!/bin/sh
# Prepare a Tier 3 review on Gemini web, following checklist.md — see ai-review.md.
# Usage: ./review.sh [--lang en|zh-Hant|vi] <feature-name> <requirements-file> <code-dir>
# Creates: review-input/review-<name>.txt (upload to Gemini, do not commit) and
#          review-<name>.md (skeleton to paste the result into).
# --lang picks the language of the AI's answer (default: en).
set -eu

LANG_CODE=en
if [ "${1:-}" = "--lang" ]; then
  [ $# -ge 2 ] || { echo "--lang needs a value: en, zh-Hant or vi" >&2; exit 2; }
  LANG_CODE=$2
  shift 2
fi

case "$LANG_CODE" in
  en) LANG_NAME='English' ;;
  zh-Hant) LANG_NAME='Traditional Chinese (繁體中文)' ;;
  vi) LANG_NAME='Vietnamese (Tiếng Việt)' ;;
  *) echo "Unsupported language: $LANG_CODE (use en, zh-Hant or vi)" >&2; exit 2 ;;
esac

if [ $# -ne 3 ]; then
  echo "Usage: $0 [--lang en|zh-Hant|vi] <feature-name> <requirements-file> <code-dir>" >&2
  exit 2
fi

NAME=$1
REQUIREMENTS=$2
CODE=$3
ROOT=$(cd "$(dirname "$0")" && pwd)
RESULT="$ROOT/review-$NAME.md"
INPUT="$ROOT/review-input/review-$NAME.txt"

[ -f "$REQUIREMENTS" ] || { echo "Requirements file not found: $REQUIREMENTS" >&2; exit 1; }
[ -d "$CODE" ] || { echo "Code directory not found: $CODE" >&2; exit 1; }
[ -e "$RESULT" ] && { echo "$RESULT already exists — not overwriting an earlier review result." >&2; exit 1; }

# Secret files: send the name only (needed for C01), never the contents.
is_secret_file() {
  case "$(basename "$1")" in
    .env|.env.*|*.pem|*.key|*.p12|*.pfx|id_rsa*|id_ed25519*) return 0 ;;
  esac
  return 1
}

FILES=$(find "$CODE" -type f \
  -not -path '*/.git/*' -not -path '*/node_modules/*' -not -path '*/dist/*' \
  -not -path '*/build/*' -not -path '*/.next/*' -not -path '*/venv/*' \
  -not -path '*/.venv/*' -not -path '*/__pycache__/*' | sort)

mkdir -p "$ROOT/review-input"

PROMPT="You are the Tier 3 reviewer in a software acceptance process. The source code below was generated by a different AI model.

This file contains: CHECKLIST, REQUIREMENTS, FILE LIST, then the contents of each code file.

Task: review the source code against exactly the 12 criteria C01–C12 in the CHECKLIST, comparing it with the REQUIREMENTS.

Mandatory rules:
- Review only against the 12 criteria. No general comments on code quality, naming or formatting.
- Do not decide whether a finding is a true or false positive, and do not judge whether the feature passes. Only record observed signs; classification belongs to a human.
- Never quote secret values, passwords or connection strings. Record the location only.
- Do not include customer, company or internal project names in the output.
- Do not invent locations. Every location must be a file and line that actually exists in the input.
- If the input is not enough to assess a criterion (e.g. no server-side code), answer \"Insufficient information\" and state what is missing. Do not guess.
- Do not rewrite or fix the source code.

Output language: write all headings and prose in $LANG_NAME.
Keep these exactly as written in English so results stay comparable across students: criterion codes (C01–C12), the answer values Yes / No / Insufficient information, the severity values High / Medium / Low, file paths, line numbers and code identifiers.

Output format (Markdown):

## Overview by criterion

| Code | Answer (Yes / No / Insufficient information) | Findings |
| --- | --- | --- |
(all 12 rows C01–C12)

## Findings

Each finding in exactly this format:

- Criterion: <code>
  Location: <file:line or function>
  Severity: High / Medium / Low (per the scale in the CHECKLIST)
  Description: <1-2 sentences>

If there are no findings, write \"No findings\".

## Open questions

List any information still needed for a complete review. If none, write \"None\".

## Plain-language summary

For a reader who is not a programmer. Use short sentences and everyday words; if a technical term is unavoidable, explain it in a few words. Base this section only on the findings above — add no new findings and give no verdict on whether the feature passes.

- What this code does: <2-3 sentences>
- Main concerns: <the most important findings, each in one plain sentence saying what could go wrong for users or the business, citing its criterion code>
- Suggested direction: pick the 1-3 most serious concerns (highest severity first). For each one, write a small heading naming the concern, then a table with 2-3 possible ways to address it (in words, no code):

  | Way | Advantages | Disadvantages |
  | --- | --- | --- |

  After each table, say which way you suggest and why, in 2-3 sentences. Always use this table; never list the ways as bullets.

If there are no findings, write \"No concerns found\" under Main concerns and skip Suggested direction."

{
  echo "===== INSTRUCTIONS ====="
  echo "$PROMPT"
  echo
  echo "===== CHECKLIST ====="
  cat "$ROOT/checklist.md"
  echo
  echo "===== REQUIREMENTS ====="
  cat "$REQUIREMENTS"
  echo
  echo "===== FILE LIST ====="
  echo "$FILES"
  echo
  echo "$FILES" | while IFS= read -r f; do
    [ -n "$f" ] || continue
    if is_secret_file "$f"; then
      echo "===== FILE: $f (secret file — contents not sent) ====="
    elif grep -Iq '' "$f" 2>/dev/null; then
      echo "===== FILE: $f ====="
      cat "$f"
      echo
    fi
  done
} > "$INPUT"

FILE_COUNT=$(echo "$FILES" | grep -c . || true)

{
  echo "# Tier 3 review — $NAME"
  echo
  echo "- Model: *(fill in the exact name recorded in ai-review.md section 2)*"
  echo "- Run date: $(date '+%Y-%m-%d')"
  echo "- Output language: $LANG_CODE"
  echo "- Requirements file: $(basename "$REQUIREMENTS")"
  echo "- Code files sent: $FILE_COUNT"
  echo "- Time waiting for Gemini's answer: *(fill in, in seconds)*"
  echo
  echo "> The result below is AI-generated and has not yet been classified true/false by a human."
  echo
  echo "<!-- Paste Gemini's answer verbatim below this line. Do not edit it, and do not re-run to get a different result. -->"
} > "$RESULT"

echo "Created:"
echo "  $INPUT  — upload this file to gemini.google.com (do not commit it)"
echo "  $RESULT  — paste Gemini's answer here"
